export enum InternAlohaScrapers {
  eightyThousandHours = '80000hours',
  acm = 'acm',
  aexpress = 'aexpress',
  angellist = 'angellist',
  apple = 'apple',
  cisco = 'cisco',
  glassdoor = 'glassdoor',
  hawaiislack = 'hawaiislack',
  idealist = 'idealist',
  indeed = 'indeed',
  linkedin = 'linkedin',
  monster = 'monster',
  nsfreu = 'nsf-reu',
  simplyHired = 'slimplyHired',
  soc = 'soc',
  zipRecruiter = 'ziprecruiter',
}
