// Admin Data Model Feeds Page
export const SET_ADMIN_DATAMODEL_FEEDS_IS_CLOUDINARY_USED = 'radgrad/shared/cloudinary/SET_ADMIN_DATAMODEL_FEEDS_IS_CLOUDINARY_USED';
export const SET_ADMIN_DATAMODEL_FEEDS_CLOUDINARY_URL = 'radgrad/shared/cloudinary/SET_ADMIN_DATAMODEL_FEEDS_CLOUDINARY_URL';
// Admin Data Model Users Page
export const SET_ADMIN_DATAMODEL_USERS_IS_CLOUDINARY_USED = 'radgrad/shared/cloudinary/SET_ADMIN_DATAMODEL_USERS_IS_CLOUDINARY_USED';
export const SET_ADMIN_DATAMODEL_USERS_CLOUDINARY_URL = 'radgrad/shared/cloudinary/SET_ADMIN_DATAMODEL_USERS_CLOUDINARY_URL';
