/* export the action types. */

export const SELECT_COURSE = 'SELECT_COURSE';
export const SELECT_COURSE_INSTANCE = 'SELECT_COURSE_INSTANCE';
export const SELECT_OPPORTUNITY = 'SELECT_OPPORTUNITY';
export const SELECT_OPPORTUNITY_INSTANCE = 'SELECT_OPPORTUNITY_INSTANCE';

export const DepSelectedTabs = {
  SELECT_PLAN: 'PLAN',
  SELECT_INSPECTOR: 'INSPECTOR',
};
