/* export the action types. */

import './paginationActionTypes';

export const SELECT_COURSE = 'SELECT_COURSE';
export const SELECT_COURSE_INSTANCE = 'SELECT_COURSE_INSTANCE';
export const SELECT_OPPORTUNITY = 'SELECT_OPPORTUNITY';
export const SELECT_OPPORTUNITY_INSTANCE = 'SELECT_OPPORTUNITY_INSTANCE';

export const CHECK_INTEGRITY_WORKING = 'CHECK_INTEGRITY_WORKING';
export const CHECK_INTEGRITY_DONE = 'CHECK_INTEGRITY_DONE';
export const DUMP_DATABASE_WORKING = 'DUMP_DATABASE_WORKING';
export const DUMP_DATABASE_DONE = 'DUMP_DATABASE_DONE';
export const GET_EMAILS_WORKING = 'GET_EMAILS_WORKING';
export const GET_EMAILS_DONE = 'GET_EMAILS_DONE';
export const TEST_EMAIL_WORKING = 'TEST_EMAIL_WORKING';
export const TEST_EMAIL_DONE = 'TEST_EMAIL_DONE';
export const LEVEL_EMAIL_WORKING = 'LEVEL_EMAIL_WORKING';
export const LEVEL_EMAIL_DONE = 'LEVEL_EMAIL_DONE';
export const ALL_EMAIL_WORKING = 'ALL_EMAIL_WORKING';
export const ALL_EMAIL_DONE = 'ALL_EMAIL_DONE';

export const DepSelectedTabs = {
  SELECT_PLAN: 'PLAN',
  SELECT_INSPECTOR: 'INSPECTOR',
};
