/* export the action types. */

export const ADVISOR_HOME_SET_COUNT = 'ADVISOR_HOME_SET_COUNT';
export const ADVISOR_HOME_SET_FIRST_NAME = 'ADVISOR_HOME_SET_FIRST_NAME';
export const ADVISOR_HOME_SET_LAST_NAME = 'ADVISOR_HOME_SET_LAST_NAME';
export const ADVISOR_HOME_SET_USERNAME = 'ADVISOR_HOME_SET_USERNAME';
export const ADVISOR_HOME_CLEAR_FILTER = 'ADVISOR_HOME_CLEAR_FILTER';
export const ADVISOR_HOME_SET_SELECTED_STUDENT_USERNAME = 'ADVISOR_HOME_SET_SELECTED_STUDENT_USERNAME';
