export const SET_ACADEMIC_PLANS_SHOW_INDEX = 'SET_ACADEMIC_PLANS_SHOW_INDEX';
export const SET_ACADEMIC_PLANS_SHOW_COUNT = 'SET_ACADEMIC_PLANS_SHOW_COUNT';
export const SET_ACADEMIC_TERMS_SHOW_INDEX = 'SET_ACADEMIC_TERMS_SHOW_INDEX';
export const SET_ACADEMIC_TERMS_SHOW_COUNT = 'SET_ACADEMIC_TERMS_SHOW_COUNT';
export const SET_ACADEMIC_YEARS_SHOW_INDEX = 'SET_ACADEMIC_YEARS_SHOW_INDEX';
export const SET_ACADEMIC_YEARS_SHOW_COUNT = 'SET_ACADEMIC_YEARS_SHOW_COUNT';
