export const pubSubLite = {
  academicPlan: 'AcademicPlanCollection',
  academicTerm: 'AcademicTermCollection',
  adminProfile: 'AdminProfileCollection',
  advisorProfile: 'AdvisorProfileCollection',
  careerGoal: 'CareerGoalCollection',
  course: 'CourseCollection',
  desiredDegree: 'DesiredDegreeCollection',
  facultyProfile: 'FacultyProfileCollection',
  helpMessage: 'HelpMessageCollection',
  interest: 'InterestCollection',
  interestType: 'InterestTypeCollection',
  mentorAnswer: 'MentorAnswerCollection',
  mentorProfile: 'MentorProfileCollection',
  mentorQuestion: 'MentorQuestionCollection',
  opportunity: 'OpportunityCollection',
  opportunityType: 'OpportunityTypeCollection',
  pageInterestsDailySnapshot: 'PageInterestsDailySnapshotCollection',
  planChoice: 'PlanChoiceCollection',
  publicStats: 'PublicStatsCollection',
  review: 'ReviewCollection',
  studentParticipation: 'StudentParticipationCollection',
  slug: 'SlugCollection',
  teaser: 'TeaserCollection',
};
