import '../imports/api/academic-term';
import '../imports/api/base';
import '../imports/api/career';
import '../imports/api/course';
import '../imports/api/degree-plan';
import '../imports/api/factoid';
import '../imports/api/ice';
import '../imports/api/integrity';
import '../imports/api/internship';
import '../imports/api/interest';
import '../imports/api/level';
import '../imports/api/opportunity';
import '../imports/api/public-stats';
import '../imports/api/radgrad';
import '../imports/api/review';
import '../imports/api/role';
import '../imports/api/slug';
import '../imports/api/star';
import '../imports/api/teaser';
import '../imports/api/test';
import '../imports/api/user';
import '../imports/api/verification';
import '../imports/api/whats-new';
import '../imports/startup/both';
import '../imports/startup/client';
import './style.css';
import 'react-datepicker/dist/react-datepicker.css';
import '../imports/ui/pages/admin'; // for jsdoc.

