/** Define IDs to identify components in the system. This is used for testing. */
export enum COMPONENTIDS {
  LANDING_EXPLORER_MENU = 'landing-explorer-menu',
  LANDING_EXPLORER_BUTTONS = 'landing-explorer-buttons',
  LANDING_CAREER_GOALS_EXPLORER = 'landing-career-goals-explorer',
  LANDING_INTERESTS_EXPLORER = 'landing-interests-explorer',
  LANDING_COURSES_EXPLORER = 'landing-courses-explorer',
  LANDING_OPPORTUNITIES_EXPLORER = 'landing-opportunities-explorer',

  NAVBAR_CURRENT_USER = 'navbar-current-user',
  NAVBAR_SIGN_OUT = 'navbar-sign-out',
  LOGIN = 'LOGIN',

  ADMIN = 'admin',
  ADMIN_MENU_HOME = 'admin-menu-home',
  ADMIN_MENU_VISIBILITY = 'admin-menu-visibility',
  ADMIN_MENU_FORECASTS = 'admin-menu-forecasts',
  ADMIN_MENU_COMMUNITY = 'admin-menu-community',
  ADMIN_MENU_EXPLORERS = 'admin-menu-explorers',
  ADMIN_MENU_EXPLORER_CAREERS = 'admin-menu-explorer-careers',
  ADMIN_MENU_EXPLORER_COURSES = 'admin-menu-explorer-courses',
  ADMIN_MENU_EXPLORER_INTERESTS = 'admin-menu-explorer-interests',
  ADMIN_MENU_EXPLORER_OPPORTUNITIES = 'admin-menu-explorer-opportunities',
  ADMIN_MENU_MANAGE = 'admin-menu-manage',
  ADMIN_MENU_MANAGE_STUDENTS = 'admin-menu-manage-students',
  ADMIN_MENU_MANAGE_VERIFICATION = 'admin-menu-manage-verification',
  ADMIN_MENU_MANAGE_REVIEW = 'admin-menu-manage-review',
  FIRST_MENU_USERNAME = 'first-menu-username',

  ADVISOR = 'advisor',
  ADVISOR_MENU_HOME = 'advisor-menu-home',
  ADVISOR_MENU_VISIBILITY = 'advisor-menu-visibility',
  ADVISOR_MENU_FORECASTS = 'advisor-menu-forecasts',
  ADVISOR_MENU_COMMUNITY = 'advisor-menu-community',
  ADVISOR_MENU_EXPLORERS = 'advisor-menu-explorers',
  ADVISOR_MENU_EXPLORER_CAREERS = 'advisor-menu-explorer-careers',
  ADVISOR_MENU_EXPLORER_COURSES = 'advisor-menu-explorer-courses',
  ADVISOR_MENU_EXPLORER_INTERESTS = 'advisor-menu-explorer-interests',
  ADVISOR_MENU_EXPLORER_OPPORTUNITIES = 'advisor-menu-explorer-opportunities',
  ADVISOR_MENU_MANAGE = 'advisor-menu-manage',
  ADVISOR_MENU_MANAGE_STUDENTS = 'advisor-menu-manage-students',
  ADVISOR_MENU_MANAGE_VERIFICATION = 'advisor-menu-manage-verification',
  ADVISOR_MENU_MANAGE_REVIEW = 'advisor-menu-manage-review',
  ADVISOR_MENU_MANAGE_OPPORTUNITIES = 'advisor-menu-manage-opportunities',

  FACULTY = 'faculty',
  FACULTY_MENU_HOME = 'faculty-menu-home',
  FACULTY_MENU_VISIBILITY = 'faculty-menu-visibility',
  FACULTY_MENU_FORECASTS = 'faculty-menu-forecasts',
  FACULTY_MENU_COMMUNITY = 'faculty-menu-community',
  FACULTY_MENU_EXPLORERS = 'faculty-menu-explorers',
  FACULTY_MENU_EXPLORER_CAREERS = 'faculty-menu-explorer-careers',
  FACULTY_MENU_EXPLORER_COURSES = 'faculty-menu-explorer-courses',
  FACULTY_MENU_EXPLORER_INTERESTS = 'faculty-menu-explorer-interests',
  FACULTY_MENU_EXPLORER_OPPORTUNITIES = 'faculty-menu-explorer-opportunities',
  FACULTY_MENU_MANAGE = 'faculty-menu-manage',
  FACULTY_MENU_MANAGE_OPPORTUNITIES = 'faculty-menu-manage-opportunities',
  FACULTY_MENU_MANAGE_VERIFICATION = 'faculty-menu-manage-verification',
  FACULTY_MENU_MANAGE_REVIEW = 'faculty-menu-manage-review',

  STUDENT = 'student',
  STUDENT_MENU_HOME = 'student-menu-home',
  STUDENT_MENU_INTERESTS = 'student-menu-interests',
  STUDENT_MENU_COURSES = 'student-menu-courses',
  STUDENT_MENU_CAREERS = 'student-menu-careers',
  STUDENT_MENU_OPPORTUNITIES = 'student-menu-opportunities',
  STUDENT_MENU_PLANNER = 'student-menu-planner',
  STUDENT_MENU_VERIFICATION = 'student-menu-verification',
  STUDENT_MENU_VISIBILITY = 'student-menu-visibility',
  STUDENT_MENU_ICE = 'student-menu-ice',
  STUDENT_MENU_LEVELS = 'student-menu-levels',
  STUDENT_MENU_REVIEWS = 'student-menu-reviews',
  STUDENT_MENU_COMMUNITY = 'student-menu-community',
  STUDENT_MENU_SIGNOUT = 'student-menu-signout',

  SIGNIN_FORM_EMAIL = 'signin-form-email',
  SIGNIN_FORM_PASSWORD = 'signin-form-password',
  SIGNIN_FORM_SUBMIT = 'signin-form-submit',

  ADD_TO_PROFILE_BUTTON = 'add-to-profile-button',
  REMOVE_FROM_PROFILE_BUTTON = 'remove-from-profile-button',
}