/** Define IDs to identify each page in the system. This is used for lastVisited, UserInteractions, and Testing. */
export enum PAGEIDS {
  ADMIN_HOME = 'admin-home-page',

  ADVISOR_HOME = 'advisor-home-page',

  ANALYTICS_LOGGED_IN_USERS = 'analytics-logged-in-users-page',
  ANALYTICS_NEWSLETTER = 'analytics-newsletter-page',
  ANALYTICS_OVERHEAD_ANALYSIS = 'analytics-overhead-analysis-page',
  ANALYTICS_STUDENT_SUMMARY = 'analytics-student-summary-page',
  ANALYTICS_USER_INTERACTIONS = 'analytics-user-interactions-page',

  DATABASE_CHECK_INTEGRITY = 'database-check-integrity-page',
  DATABASE_DUMP_DATABASE = 'database-dump-database-page',

  DATA_MODEL_ACADEMIC_TERMS = 'data-model-academic-terms-page',
  DATA_MODEL_ACADEMIC_YEARS = 'data-model-academic-year-instances-page',
  DATA_MODEL_CAREER_GOALS = 'data-model-career-goals-page',
  DATA_MODEL_COURSE_INSTANCES = 'data-model-course-instances-page',
  DATA_MODEL_COURSES = 'data-model-courses-page',
  DATA_MODEL_INTERESTS = 'data-model-interests-page',
  DATA_MODEL_INTEREST_TYPES = 'data-model-interest-types-page',
  DATA_MODEL_OPPORTUNITIES = 'data-model-opportunities-page',
  DATA_MODEL_OPPORTUNITY_INSTANCES = 'data-model-opportunity-instances-page',
  DATA_MODEL_OPPORTUNITY_TYPES = 'data-model-opportunity-types-page',
  DATA_MODEL_REVIEWS = 'data-model-reviews-page',
  DATA_MODEL_SLUGS = 'data-model-slugs-page',
  DATA_MODEL_TEASERS = 'data-model-teasers-page',
  DATA_MODEL_USERS = 'data-model-users-page',
  DATA_MODEL_VERIFICATION_REQUESTS = 'data-model-verification-requests-page',

  FACULTY_HOME_PAGE = 'faculty-home-page',
  FACULTY_VERIFICATION_PAGE = 'faculty-verification-page',

  LANDING_CAREER_GOAL_EXPLORER = 'landing-career-goal-explorer-page',
  LANDING_CAREER_GOALS_EXPLORER = 'landing-career-goals-explorer-page',
  LANDING_COURSE_EXPLORER = 'landing-course-explorer-page',
  LANDING_COURSES_EXPLORER = 'landing-courses-explorer-page',
  LANDING_HOME = 'landing-home-page',
  LANDING_INTEREST_EXPLORER = 'landing-interest-explorer-page',
  LANDING_INTERESTS_EXPLORER = 'landing-interests-explorer-page',
  LANDING_OPPORTUNITIES_EXPLORER = 'landing-opportunities-explorer-page',
  LANDING_OPPORTUNITY_EXPLORER = 'landing-opportunity-explorer-page',

  STUDENT_DEGREE_PLANNER = 'degree-planner-page',
  STUDENT_HOME = 'student-home-page',
  STUDENT_ICE = 'student-ice-points-page',
  STUDENT_LEVELS = 'student-levels-page',
  STUDENT_REVIEWS = 'student-reviews-page',
  STUDENT_VERIFICATION = 'student-verification-page',
  STUDENT_VISIBILITY = 'student-visibility-page',

  CAREER_GOAL = 'career-goal-page',
  CAREER_GOAL_BROWSER = 'career-goal-browser-view-page',
  COMMUNITY = 'community-page',
  COURSE = 'course-page',
  COURSE_BROWSER = 'course-browser-view-page',
  FORECASTS = 'forecasts-page',
  INTEREST = 'interest-page',
  INTEREST_BROWSER = 'interest-browser-view-page',
  MANAGE_STUDENTS = 'manage-students-page',
  OPPORTUNITY = 'opportunity-page',
  OPPORTUNITY_BROWSER = 'opportunity-browser-view-page',
  MANAGE_OPPORTUNITIES = 'manage-opportunities-page',
  MANAGE_REVIEWS = 'manage-reviews-page',
  MANAGE_VERIFICATION = 'manage-verification-page',
  TERMS_AND_CONDITIONS = 'terms-and-conditions-page',
  VISIBILITY = 'visibility-page',
}