/** Define IDs to identify each page in the system. This is used for lastVisited, UserInteractions, and Testing. */
export enum PAGEIDS {
  ADMIN_HOME = 'admin-home-page',
  ADMIN_DATABASE = 'admin-database-page',
  ADMIN_DATA_MODEL = 'admin-data-model-page',
  ADMIN_MODERATION = 'admin-moderation-page',

  ADVISOR_HOME = 'advisor-home-page',
  ADVISOR_VERIFICATIONS = 'advisor-verification-requests-page',
  ADVISOR_MODERATION = 'advisor-moderation-page',

  ALUMNI_HOME = 'alumni-home-page',

  ANALYTICS_LOGGED_IN_USERS = 'analytics-logged-in-users-page',
  ANALYTICS_NEWSLETTER = 'analytics-newsletter-page',
  ANALYTICS_BEHAVIOR_TABLE = 'analytics-behavior-table-page',

  DATABASE_MANAGEMENT = 'manage-database-page',

  DATA_MODEL_ACADEMIC_TERMS = 'data-model-academic-terms-page',
  DATA_MODEL_ACADEMIC_YEARS = 'data-model-academic-year-instances-page',
  DATA_MODEL_CAREER_GOALS = 'data-model-career-goals-page',
  DATA_MODEL_CAREER_GOAL_KEYWORDS = 'data-model-career-goal-keywords-page',
  DATA_MODEL_COURSE_INSTANCES = 'data-model-course-instances-page',
  DATA_MODEL_COURSES = 'data-model-courses-page',
  DATA_MODEL_INTERESTS = 'data-model-interests-page',
  DATA_MODEL_INTEREST_KEYWORDS = 'data-model-interest-keywords-page',
  DATA_MODEL_INTEREST_TYPES = 'data-model-interest-types-page',
  DATA_MODEL_INTERNSHIPS = 'data-model-internships-page',
  DATA_MODEL_OPPORTUNITIES = 'data-model-opportunities-page',
  DATA_MODEL_OPPORTUNITY_INSTANCES = 'data-model-opportunity-instances-page',
  DATA_MODEL_OPPORTUNITY_TYPES = 'data-model-opportunity-types-page',
  DATA_MODEL_REVIEWS = 'data-model-reviews-page',
  DATA_MODEL_SLUGS = 'data-model-slugs-page',
  DATA_MODEL_TEASERS = 'data-model-teasers-page',
  DATA_MODEL_USERS = 'data-model-users-page',
  DATA_MODEL_VERIFICATION_REQUESTS = 'data-model-verification-requests-page',

  FACULTY_HOME_PAGE = 'faculty-home-page',
  FACULTY_VERIFICATION_PAGE = 'faculty-verification-page',

  LANDING_CAREER_GOAL_EXPLORER = 'landing-career-goal-explorer-page',
  LANDING_CAREER_GOALS_EXPLORER = 'landing-career-goals-explorer-page',
  LANDING_COURSE_EXPLORER = 'landing-course-explorer-page',
  LANDING_COURSES_EXPLORER = 'landing-courses-explorer-page',
  LANDING_HOME = 'landing-home-page',
  LANDING_INTEREST_EXPLORER = 'landing-interest-explorer-page',
  LANDING_INTERESTS_EXPLORER = 'landing-interests-explorer-page',
  LANDING_OPPORTUNITIES_EXPLORER = 'landing-opportunities-explorer-page',
  LANDING_OPPORTUNITY_EXPLORER = 'landing-opportunity-explorer-page',

  STUDENT_DEGREE_PLANNER = 'degree-planner-page',
  STUDENT_HOME = 'student-home-page',
  STUDENT_ICE = 'student-ice-points-page',
  STUDENT_LEVELS = 'student-levels-page',
  STUDENT_REVIEWS = 'student-reviews-page',
  STUDENT_VERIFICATION = 'student-verification-page',
  STUDENT_VISIBILITY = 'student-visibility-page',

  ONBOARD_ANDRE = 'onboard-andre-page',
  ONBOARD_CALIANA = 'onboard-caliana-page',
  ONBOARD_TIMOTHY = 'onboard-timothy-page',
  ONBOARD_TREY = 'onboard-trey-page',
  ONBOARD_SHINYA = 'onboard-andre-page',

  CAREER_GOAL = 'career-goal-page',
  CAREER_GOAL_BROWSER = 'career-goal-browser-view-page',
  INTERNSHIP_BROWSER = 'internship-browser-view-page',
  INTERNSHIP = 'internship-page',
  COMMUNITY = 'community-page',
  COURSE = 'course-page',
  COURSE_BROWSER = 'course-browser-view-page',
  FORECASTS = 'forecasts-page',
  INTEREST = 'interest-page',
  INTEREST_BROWSER = 'interest-browser-view-page',
  MANAGE_INTERNSHIPS = 'manage-internship-page',
  MANAGE_OPPORTUNITIES = 'manage-opportunities-page',
  MANAGE_REVIEWS = 'manage-reviews-page',
  MANAGE_STUDENTS = 'manage-students-page',
  MANAGE_VERIFICATION = 'manage-verification-page',
  OPPORTUNITY = 'opportunity-page',
  OPPORTUNITY_BROWSER = 'opportunity-browser-view-page',
  SIGNOUT = 'signout-page',
  TERMS_AND_CONDITIONS = 'terms-and-conditions-page',
  VISIBILITY = 'visibility-page',
}
