language: node_js
sudo: required
node_js:
  - "0.10"
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
env:
  global:
    - TEST_COMMAND=meteor
  matrix:
    - METEOR_RELEASE=1.4.4.5
    - METEOR_RELEASE=1.5.4.1
    - METEOR_RELEASE=1.6.1
    - METEOR_RELEASE=1.7-rc.12