export const GET_EMAILS_WORKING = 'GET_EMAILS_WORKING';
export const GET_EMAILS_DONE = 'GET_EMAILS_DONE';
export const TEST_EMAIL_WORKING = 'TEST_EMAIL_WORKING';
export const TEST_EMAIL_DONE = 'TEST_EMAIL_DONE';
export const LEVEL_EMAIL_WORKING = 'LEVEL_EMAIL_WORKING';
export const LEVEL_EMAIL_DONE = 'LEVEL_EMAIL_DONE';
export const ALL_EMAIL_WORKING = 'ALL_EMAIL_WORKING';
export const ALL_EMAIL_DONE = 'ALL_EMAIL_DONE';
