export const GET_EMAILS_WORKING = 'radgrad/admin/analytics/GET_EMAILS_WORKING';
export const GET_EMAILS_DONE = 'radgrad/admin/analytics/GET_EMAILS_DONE';
export const TEST_EMAIL_WORKING = 'radgrad/admin/analytics/TEST_EMAIL_WORKING';
export const TEST_EMAIL_DONE = 'radgrad/admin/analytics/TEST_EMAIL_DONE';
export const LEVEL_EMAIL_WORKING = 'radgrad/admin/analytics/LEVEL_EMAIL_WORKING';
export const LEVEL_EMAIL_DONE = 'radgrad/admin/analytics/LEVEL_EMAIL_DONE';
export const ALL_EMAIL_WORKING = 'radgrad/admin/analytics/ALL_EMAIL_WORKING';
export const ALL_EMAIL_DONE = 'radgrad/admin/analytics/ALL_EMAIL_DONE';
// Admin Analytics Overhead Analysis
export const SET_OVERHEAD_ANALYSIS_DATE_RANGE = 'radgrad/admin/analytics/SET_OVERHEAD_ANALYSIS_DATE_RANGE';
export const SET_OVERHEAD_ANALYSIS_OVERHEAD_BUCKETS = 'radgrad/admin/analytics/SET_OVERHEAD_ANALYSIS_OVERHEAD_BUCKETS';
export const SET_OVERHEAD_ANALYSIS_USER_INTERACTIONS = 'radgrad/admin/analytics/SET_OVERHEAD_ANALYSIS_USER_INTERACTIONS';
export const SET_OVERHEAD_ANALYSIS_OVERHEAD_DATA = 'radgrad/admin/analytics/SET_OVERHEAD_ANALYSIS_OVERHEAD_DATA';
// Admin Analytics Student Summary
export const SET_STUDENT_SUMMARY_DATE_RANGE = 'radgrad/shared/datepicker/SET_STUDENT_SUMMARY_DATE_RANGE';
