name: ci-radgrad

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Cache node modules
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-node-modules
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-build-v7-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - run: npm ci --legacy-peer-deps

      - run: npm install --location=global meteor

      - name: install
        shell: bash -l {0}
        run: meteor npm install

      - name: lint
        shell: bash -l {0}
        run: meteor npm run lint

      - name: unimported
        shell: bash -l {0}
        run: meteor npm run unimported

      - name: test-unit
        shell: bash -l {0}
        run: meteor npm run test-unit

      - name: test-integration
        shell: bash -l {0}
        run: meteor npm run test-integration

      - name: test-acceptance
        shell: bash -l {0}
        run: meteor npm run test-acceptance
